// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace Jamstack.On.Dotnet.Models
{
    public partial class Cta
    {
        public const string Codename = "cta";
        public const string LabelCodename = "label";
        public const string RoleCodename = "role";
        public const string UrlCodename = "url";

        public string Label { get; set; }
        public IEnumerable<IMultipleChoiceOption> Role { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public string Url { get; set; }
    }
}