// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace Jamstack.On.Dotnet.Models
{
    public partial class LandingPage
    {
        public const string Codename = "landing_page";
        public const string CtaCodename = "cta";
        public const string HeadlineCodename = "headline";
        public const string ImagesCodename = "images";
        public const string MainTextCodename = "main_text";
        public const string SummaryCodename = "summary";

        public IEnumerable<object> Cta { get; set; }
        public string Headline { get; set; }
        public IRichTextContent Images { get; set; }
        public IRichTextContent MainText { get; set; }
        public IRichTextContent Summary { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}