// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace Jamstack.On.Dotnet.Models
{
    public partial class LogoAsset
    {
        public const string Codename = "logo_asset";
        public const string LogoCodename = "logo";
        public const string OptionsCodename = "options";
        public const string UrlCodename = "url";

        public IEnumerable<IAsset> Logo { get; set; }
        public IEnumerable<IMultipleChoiceOption> Options { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public string Url { get; set; }
    }
}